import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Logo from "styles/assets/logo";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col justify-between min-h-screen">
        <header>
          <div className="flex justify-center p-7">
            <Logo />
          </div>
        </header>
        <main></main>

        <footer className=" p-7 bg-[#4A3353] text-white flex justify-center text-sm">
          <div>
            <p>
              <span className=" font-bold">©2022, Altaria Hub.</span> All Rights
              Reserved | Designed by{" "}
              <span className=" font-bold">Shodipo Michael.</span>
            </p>
          </div>
        </footer>
      </div>
    </div>
  );
};

export default Home;
