import Input from "components/formElements/input";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Logo from "assets/logo";
import Profile from "assets/profile";
import Envelop from "assets/envelop";
import { Checkbox } from "@mantine/core";
import { useState } from "react";
import { MainFormType } from "types";
import axios from "axios";
import { baseURL } from "config/constants";
import { Loader } from "@mantine/core";

const Home: NextPage = () => {
  const [isLoading, setIsLoading] = useState(false);
  const [payload, setPayload] = useState<MainFormType>({
    fullName: "",
    email: "",
    all: false,
    logistics: false,
    vendor: false,
    community: false,
    events: false,
    donations: false,
    customer: false,
  });

  const canProceed =
    payload.fullName &&
    payload.email &&
    (payload.all ||
      payload.logistics ||
      payload.customer ||
      payload.vendor ||
      payload.events ||
      payload.donations ||
      payload.community);

  const submit = async () => {
    try {
      setIsLoading(true);
      const body = {
        fullName: payload.fullName,
        email: payload.email,
        actions: Object.keys(payload).filter(
          //@ts-ignore
          (key: string) => payload[key] === true
        ),
      };
      console.log(body);
      const { data } = await axios.post(baseURL + "/interests", body);
      console.log(data);
    } catch (error) {
      console.log(error);
    } finally {
      setIsLoading(false);
    }
  };
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col justify-between min-h-screen">
        <header className=" fixed w-screen top-0 bg-white z-50">
          <div className="flex justify-center p-7">
            <Logo />
          </div>
        </header>
        <main className="flex-1 px-[10vw] flex justify-center mt-32">
          <div className=" mt-9 w-full max-w-3xl">
            <h2 className=" text-center text-[#4A3353] text-xl md:text-4xl font-bold ">
              Please fill out the information below
            </h2>
            <section className=" mb-12 mt-12">
              <Input
                icon={Profile}
                value={payload?.fullName}
                placeholder="Enter Full Name"
                onChange={(e: any) =>
                  setPayload({ ...payload, fullName: e.target.value })
                }
              />
              <Input
                placeholder="Enter Email Address"
                icon={Envelop}
                value={payload?.email}
                onChange={(e: any) =>
                  setPayload({ ...payload, email: e.target.value })
                }
              />
            </section>

            <section className=" mb-12">
              <h3 className=" text-center text-[#4A3353] text-xl md:text-4xl font-bold mb-4">
                What would you like to do on Altaria Hub?
              </h3>
              {/* <Input /> */}
              <div className="border-2 border-[#E4E0E5] p-5 font-semibold text-[#4A3353] rounded-lg mb-4 flex gap-2 w-fit">
                <Checkbox
                  label="Select all options"
                  className=" text-sm md:text-base cursor-pointer"
                  color="#FF4B0D"
                  checked={
                    //@ts-ignore
                    payload?.all
                  }
                  onChange={(e) =>
                    //@ts-ignore
                    setPayload({ ...payload, all: e.currentTarget.checked })
                  }
                />
              </div>
              {[
                { label: "Register my Logistics Company", value: "logistics" },
                { label: "Sign up to Sell Products", value: "vendor" },

                { label: "Register as a Customer", value: "customer" },

                { label: "Host my event on Altaria Hub", value: "events" },
                { label: "Register my Donation Centre", value: "donations" },
                {
                  label: "Host my community on Altaria Hub",
                  value: "community",
                },
              ].map((item, idx) => (
                <div
                  key={`${item.label}_${idx}`}
                  className="border-2 border-[#E4E0E5] w-full p-5 font-semibold text-[#4A3353] rounded-lg mb-4 flex gap-2"
                >
                  <Checkbox
                    label={item.label}
                    className="text-sm md:text-base cursor-pointer"
                    color="#FF4B0D"
                    checked={
                      //@ts-ignore
                      payload[item.value] || payload.all
                    }
                    onChange={(e) =>
                      //@ts-ignore
                      setPayload({
                        ...payload,
                        [item.value]: e.currentTarget.checked,
                      })
                    }
                  />
                </div>
              ))}
              <div className="mt-10 flex justify-center">
                <button
                  className={`font-semibold text-white bg-[#FF4B0D] px-12 py-4 rounded-xl flex gap-2 items-center ${
                    canProceed || !isLoading
                      ? ""
                      : "opacity-70 cursor-not-allowed"
                  } `}
                  disabled={!canProceed || isLoading}
                  onClick={submit}
                >
                  <p>Submit</p>
                  {isLoading && <Loader size={15} color="white" />}
                </button>
              </div>
            </section>
          </div>
        </main>

        <footer className=" p-7 bg-[#4A3353] text-white flex justify-center text-sm">
          <div>
            <p className="flex justify-center items-center flex-col md:flex-row">
              <span>
                <span className=" text-xs md:text-base font-bold">
                  ©2022, Altaria Hub.
                </span>{" "}
                All Rights Reserved | Designed by
              </span>
              <span className=" font-bold">Shodipo Michael.</span>
            </p>
          </div>
        </footer>
      </div>
    </div>
  );
};

export default Home;
